version: "3.9"

services:
  db_service:
    build:
      context: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_service:
    build:
      context: ./srv
    ports:
      - "5000:5000"
    depends_on:
      - db_service

volumes:
  postgres_data:
    name: postgres_data
